language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test evap.evaluation evap.staff evap.contributor evap.results evap.student evap.rewards evap.staff.tests.TestDataTest.load_test_data
after_success:
  - coveralls
