language: python
python:
  - "3.4"
services:
- postgresql
before_script:
  - psql -c 'create database evap;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test evap.evaluation evap.staff evap.contributor evap.results evap.student evap.grades evap.rewards evap.evaluation.tests.test_misc.TestDataTest.load_test_data
after_success:
  - coveralls
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
